BEGIN
  FOR i IN (SELECT table_name FROM user_tables WHERE table_name = 'A_SHOP') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE A_SHOP';
  END LOOP;
END;
/
CREATE TABLE A_SHOP (
	SID			NUMBER(4, 0) NOT NULL,
	MID			NUMBER(4, 0) NOT NULL,
	NAME 		VARCHAR2(50) NOT NULL,
	DESCRIPTION	VARCHAR2(50),
	IMG_PATH	VARCHAR2(100),
	CONSTRAINT A_SHOP_IDX1 PRIMARY KEY (SID)
)
/
CREATE SEQUENCE A_SHOP_SEQ START WITH 1 INCREMENT BY 1;
/