BEGIN
  FOR i IN (SELECT table_name FROM user_tables WHERE table_name = 'A_ADMIN') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE A_ADMIN';
  END LOOP;
END;
/
CREATE TABLE A_ADMIN (
	AID			VARCHAR2(10) NOT NULL,
	PASSOWRD	VARCHAR2(64) NOT NULL,
	CONSTRAINT A_ADMIN_IDX1 PRIMARY KEY (AID)
)
/