BEGIN
  FOR i IN (SELECT table_name FROM user_tables WHERE table_name = 'A_MERCHANT') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE A_MERCHANT';
  END LOOP;
END;
/
CREATE TABLE A_MERCHANT (
	MID			NUMBER(4, 0) NOT NULL,
	NAME		VARCHAR2(30) NOT NULL,
	AGE			NUMBER(3, 0),
	GENDER		VARCHAR2(2),
	STATUS		VARCHAR2(10),
	DESCRIPTION	VARCHAR2(50),
	REG_DATE	DATE,
	IMG_PATH	VARCHAR2(100),
	CONSTRAINT A_MERCHANT_IDX1 PRIMARY KEY (MID)
)
/