BEGIN
  FOR i IN (SELECT table_name FROM user_tables WHERE table_name = 'A_MERCHANT') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE A_MERCHANT';
  END LOOP;
END;
/
CREATE TABLE A_MERCHANT (
	MID			NUMBER(4, 0) NOT NULL,
	NAME		VARCHAR2(30) NOT NULL,
	BRITH_DATE	DATE,
	GENDER		VARCHAR2(8),
	STATUS		VARCHAR2(10),
	REG_DATE	DATE,
	CONSTRAINT A_MERCHANT_IDX1 PRIMARY KEY (MID)
)
/