BEGIN
  FOR i IN (SELECT table_name FROM user_tables WHERE table_name = 'A_DISH') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE A_DISH';
  END LOOP;
END;
/
CREATE TABLE A_DISH (
	DID			NUMBER(5, 0) NOT NULL,
	NAME		VARCHAR2(20) NOT NULL,
	TYPE		VARCHAR2(20),
	PRICE		NUMBER(5, 1),
	SID			NUMBER(4, 0),
	IS_ACTIVE	NUMBER(1, 0) NOT NULL,
	CONSTRAINT A_DISH_IDX1 PRIMARY KEY (DID)
)
/