BEGIN
  FOR i IN (SELECT table_name FROM user_tables WHERE table_name = 'M_MERCHANT_CONTACT') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE M_MERCHANT_CONTACT';
  END LOOP;
END;
/
CREATE TABLE M_MERCHANT_CONTACT (
	CID		NUMBER(4, 0) NOT NULL,
	MID		NUMBER(4, 0) NOT NULL,
	TYPE	VARCHAR2(10) NOT NULL,
	INFO	VARCHAR2(50) NOT NULL,
	CONSTRAINT M_MERCHANT_CONTACT_IDX1 PRIMARY KEY (CID)
)
/
CREATE SEQUENCE M_MERCHANT_CONTACT_SEQ START WITH 1 INCREMENT BY 1;
/