BEGIN
  FOR i IN (SELECT table_name FROM user_tables WHERE table_name = 'M_SHOP_CONTACT') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE M_SHOP_CONTACT';
  END LOOP;
END;
/
CREATE TABLE M_SHOP_CONTACT (
	CID		NUMBER(4, 0) NOT NULL,
	SID		NUMBER(4, 0) NOT NULL,
	TYPE	VARCHAR2(10) NOT NULL,
	INFO	VARCHAR2(50) NOT NULL,
	CONSTRAINT M_SHOP_CONTACT_IDX1 PRIMARY KEY (CID)
)
/
CREATE SEQUENCE M_SHOP_CONTACT_SEQ START WITH 1 INCREMENT BY 1;
/