BEGIN
  FOR i IN (SELECT table_name FROM user_tables WHERE table_name = 'M_DISH') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE M_DISH';
  END LOOP;
END;
/
CREATE TABLE M_DISH (
	DID			NUMBER(5, 0) NOT NULL,
	NAME		VARCHAR2(20) NOT NULL,
	TYPE		VARCHAR2(20),
	PRICE		NUMBER(5, 1),
	SID			NUMBER(4, 0),
	IS_ACTIVE	NUMBER(1, 0) NOT NULL,
	CONSTRAINT M_DISH_IDX1 PRIMARY KEY (DID)
)
/
CREATE SEQUENCE M_DISH_SEQ START WITH 1 INCREMENT BY 1;
/